annotations:
  category: Database
apiVersion: v2
appVersion: 6.0.3
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 2.x.x
description: MongoDB(R) is a relational open source NoSQL database. Easy to use, it
  stores data in JSON-like documents. Automated scalability and high-performance.
  Ideal for developing cloud native applications.
home: https://github.com/bitnami/charts/tree/main/bitnami/mongodb
icon: https://bitnami.com/assets/stacks/mongodb/img/mongodb-stack-220x234.png
keywords:
- mongodb
- database
- nosql
- cluster
- replicaset
- replication
maintainers:
- name: Bitnami
  url: https://github.com/bitnami/charts
name: mongodb
sources:
- https://github.com/bitnami/containers/tree/main/bitnami/mongodb
- https://mongodb.org
version: 13.6.2
