image: 
  repository: docker.io/quanxiang/persona
  tag: v2.0.0
namespace: ""
elastic: {}
imagePullSecrets: ""

service:
  type: ClusterIP
  port: 80
  rpcPort: 0

app:
  kubernetes:
    io:
      name: lowcode
