kind: Deployment
apiVersion: apps/v1
metadata:
  name: kibana
  namespace: {{ .Values.namespace }}
  labels:
    app: kibana
  annotations:
    deployment.kubernetes.io/revision: '1'
    kubesphere.io/creator: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kibana
      annotations:
        logging.kubesphere.io/logsidecar-config: '{}'
    spec:
      volumes:
        - name: volume-zuhjax
          configMap:
            name: kibana
            defaultMode: 420
      containers:
        - name: container-q54rb6
          image: 'kibana:7.16.1'
          ports:
            - name: http-5601
              containerPort: 5601
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: volume-zuhjax
              readOnly: true
              mountPath: /usr/share/kibana/config
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: default
      serviceAccount: default
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
