kind: Service
apiVersion: v1
metadata:
  name: kibana
  namespace: {{ .Values.namespace }}
  labels:
    app: kibana
  annotations:
    kubesphere.io/creator: admin
spec:
  ports:
    - name: http-5601
      protocol: TCP
      port: 5601
      targetPort: 5601
  selector:
    app: kibana
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
