apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.names.fullname" . }}-headless
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: tcp-redis
      port: {{ .Values.redis.containerPorts.redis }}
      targetPort: tcp-redis
    - name: tcp-redis-bus
      port: {{ .Values.redis.containerPorts.bus }}
      targetPort: tcp-redis-bus
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
