kind: Secret
apiVersion: v1
type: kubernetes.io/ssh-auth
metadata:
  name: {{ .Values.git.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    tekton.dev/git-0: {{ .Values.git.host }}
data:
  known_hosts: >-
   {{ .Values.git.known_hosts_scan }}
  ssh-privatekey: >-
   {{ .Values.git.sshPrivatekey }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ .Values.docker.name }}
  namespace: {{ .Values.namespace }}
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}