{{- if (include "elasticsearch.createSecret" . ) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if .Values.security.elasticPassword }}
  elasticsearch-password: {{ default "" .Values.security.elasticPassword | b64enc | quote }}
  {{- else }}
  elasticsearch-password: {{ randAlphaNum 14 | b64enc | quote }}
  {{- end }}
  {{- if .Values.security.tls.keystorePassword }}
  keystore-password: {{ default "" .Values.security.tls.keystorePassword | b64enc | quote }}
  {{- end }}
  {{- if .Values.security.tls.truststorePassword }}
  truststore-password: {{ default "" .Values.security.tls.truststorePassword | b64enc | quote }}
  {{- end }}
  {{- if .Values.security.tls.keyPassword }}
  key-password: {{ default "" .Values.security.tls.keyPassword | b64enc | quote }}
  {{- end }}
---
{{- end }}
{{- if (include "elasticsearch.createTlsPasswordsSecret" . ) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}-tls-pass
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if .Values.security.tls.keystorePassword }}
  truststore-password: {{ default "" .Values.elasticPassword | b64enc | quote }}
  {{- end }}
  {{- if .Values.security.tls.truststorePassword }}
  keystore-password: {{ default "" .Values.elasticPassword | b64enc | quote }}
  {{- end }}
  {{- if .Values.security.tls.elasticPassword }}
  key-password: {{ default "" .Values.elasticPassword | b64enc | quote }}
  {{- end }}
{{- end }}
