kind: Deployment
apiVersion: apps/v1
metadata:
  name: fileserver
  namespace: {{ .Release.Namespace }}
  labels:
    app: fileserver
    app.kubernetes.io/name: {{ .Values.app.kubernetes.io.name }}
    app.kubernetes.io/version: v1
    version: v1
  annotations:
    deployment.kubernetes.io/revision: '1'
    servicemesh.kubesphere.io/enabled: 'false'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fileserver
      app.kubernetes.io/name: {{ .Values.app.kubernetes.io.name }}
      app.kubernetes.io/version: v1
      version: v1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fileserver
        app.kubernetes.io/name: {{ .Values.app.kubernetes.io.name }}
        app.kubernetes.io/version: v1
        version: v1
      annotations:
        kubesphere.io/containerSecrets: '{"container":"docker-registry"}'
        logging.kubesphere.io/logsidecar-config: '{}'
        sidecar.istio.io/inject: 'false'
    spec:
      volumes:
        - name: volume
          configMap:
            name: fileserver
            defaultMode: 420
      containers:
        - name: container
          image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
          args:
          {{- if eq .Values.storage.type "minio" }}
            - '--accesskey={{ .Values.storage.accessKey }}'
            - '--secretkey={{ .Values.storage.secretKey }}'
            - '--endpoint={{ .Values.storage.endpoint }}'
            - '--region={{ .Values.storage.location }}'
          {{- end }}
          ports:
            - name: fileserver
              containerPort: 80
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: volume
              readOnly: true
              mountPath: /configs
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: default
      serviceAccount: default
      {{- if .Values.hostAliases.enabled }}
      hostAliases: 
        - ip: {{ .Values.hostAliases.loadBalancerIP }}
          hostnames:
            {{- range .Values.hostAliases.hostnames }}
            - {{ . | quote }}
            {{- end }}
      {{- end }}
      securityContext: {}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      affinity: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

