image:
  repository: docker.io/quanxiang/faas
  tag: v2.0.0
namespace: ""
imagePullSecrets: ""
goBuildImage: docker.io/quanxiang/builder-go:v1.16
mysql: {}

redis: {}
kafka: {}
elastic: {}

service:
  type: ClusterIP
  port: 80
  rpcPort: 0
app:
  kubernetes:
    io:
      name: lowcode