image:
  repository: docker.io/quanxiang/flow
  tag: v2.0.0
namespace: ""
imagePullSecrets: ""
service:
  type: ClusterIP
  port: 80
  rpcPort: 9081
mysql: {}
redis: {}

kafka:
  broker:
  - kafka:9092

app:
  kubernetes:
    io:
      name: backend


