kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: polyapi-qxp
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 30m
spec:
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ .host | quote }}
    http:
      paths:
      {{- range .paths }}
      - path: {{ .path }}
        pathType: Prefix
        backend:
          service:
            name: {{ .fullName }}
            port:
              number: {{ .svcPort }}
      {{- end }}
  {{- end }}
