# Default values for implant.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: docker.io/quanxiang/implant
  tag: v2.0.0
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.

namespace: ""
imagePullSecrets: ""
service:
  type: ClusterIP
  port: 80

app:
  kubernetes:
    io:
      name: lowcode