apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: message-kafka-pubsub
  namespace: {{ .Values.namespace }}
spec:
  type: pubsub.kafka
  version: v1
  metadata:
      # Kafka broker connection setting
    - name: brokers
      value: '{{ join "," .Values.config.kafka.broker }}'
    - name: authRequired
      value: "false"
    - name: authType # Required.
      value: "none"
    - name: maxMessageBytes
      value: 10240
    - name: disableTls
      value: "true"