apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: message-email
  namespace: {{ .Values.namespace }}
spec:
  topic: lowcode.Email
  route:  /send
  pubsubname: message-kafka-pubsub
scopes:
- email