{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "builder.serviceAccountName" . }}
  labels:
    {{- include "builder.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
secrets:
  {{- with .Values.dockerConfig }}
  - name: {{ .name }}
  {{- end }}
  {{- with .Values.gitSSH }}
  - name: {{ .name }}
  {{- end }}
{{- end }}
