kind: Deployment
apiVersion: apps/v1
metadata:
  name: fileserver
  namespace: {{ .Values.namespace }}
  labels:
    app: fileserver
    app.kubernetes.io/name: {{ .Values.app.kubernetes.io.name }}
    app.kubernetes.io/version: v1
    version: v1
  annotations:
    deployment.kubernetes.io/revision: '1'
    servicemesh.kubesphere.io/enabled: 'false'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fileserver
      app.kubernetes.io/name: {{ .Values.app.kubernetes.io.name }}
      app.kubernetes.io/version: v1
      version: v1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fileserver
        app.kubernetes.io/name: {{ .Values.app.kubernetes.io.name }}
        app.kubernetes.io/version: v1
        version: v1
      annotations:
        kubesphere.io/containerSecrets: '{"container":"docker-registry"}'
        logging.kubesphere.io/logsidecar-config: '{}'
        sidecar.istio.io/inject: 'false'
    spec:
      volumes:
        - name: volume
          configMap:
            name: fileserver
            defaultMode: 420
      containers:
        - name: container
          image: '{{ .Values.image.repo }}/{{ .Values.image.name }}:{{ .Values.image.tag }}'
          args:
            - '--accesskey=Minio'
            - '--secretkey=Minio123456'
            - '--endpoint=http://fs.{{ .Values.args.endpoint }}'
            - '--region=us-east-1'
          ports:
            - name: fileserver
              containerPort: 80
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: volume
              readOnly: true
              mountPath: /configs
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: default
      serviceAccount: default
      {{- if .Values.args.enabled }}
      hostAliases:
        - hostnames:
            - fs.{{ .Values.domain }}
            - default.fs.{{ .Values.domain }}
          ip: {{ .Values.args.ip }}
      {{- end }}
      securityContext: {}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      affinity: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

