{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "serving.serviceAccountName" . }}
  labels:
    {{- include "serving.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if .Values.serviceAccount.secrets }}
secrets:
  {{- range .Values.serviceAccount.secrets }}
  - name: {{ .name }}
  {{- end }}
{{- end }}
{{- end }}