{{- if (empty .Values.existingConfigMap) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fluent-bit.fullname" . }}-config
  labels:
    app: {{ template "fluent-bit.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  fluent-bit-service.conf: |
    [Service]
        Parsers_File    parsers.conf

  fluent-bit-input.conf: |
    [Input]
        Name    tail
        Path    /var/log/containers/*_builder_*.log
        Exclude_Path    /var/log/containers/*_kubesphere-logging-system_events-exporter*.log,/var/log/containers/kube-auditing-webhook*_kubesphere-logging-system_kube-auditing-webhook*.log,/var/log/containers/*fluent-bit*.log
        Refresh_Interval    10
        Skip_Long_Lines    true
        DB    /fluent-bit/tail/pos.db
        DB.Sync    Normal
        Mem_Buf_Limit    5MB
        Parser    docker
        Tag    kube.*

  fluent-bit-filter.conf: |
    [Filter]
        Name    kubernetes
        Match    kube.*
        Kube_URL    https://kubernetes.default.svc:443
        Kube_CA_File    /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File    /var/run/secrets/kubernetes.io/serviceaccount/token
        Labels   true
        Annotations    false
    [Filter]
        Name    nest
        Match    kube.*
        Operation    lift
        Nested_under    kubernetes
        Add_prefix    kubernetes_
    [Filter]
        Name    modify
        Match    kube.*
        Remove    stream
        Remove    kubernetes_pod_id
        Remove    kubernetes_host
        Remove    kubernetes_container_hash
    [Filter]
        Name    nest
        Match    kube.*
        Operation    nest
        Wildcard    kubernetes_*
        Nest_under    kubernetes
        Remove_prefix    kubernetes_
    [Filter]
        Name    lua
        Match    service.*
        script    /fluent-bit/config/systemd.lua
        call    add_time
        time_as_table    true
    [Filter]
        Name    parser
        Match    kube_events
        Key_Name    log
        Parser    json


  fluent-bit-output.conf: |
    [Output]
        Name    es
        Match_Regex    (?:kube|service)\.(.*)
        Host    {{ .Values.elastic.host }}
        Port    {{ .Values.elastic.port }}
        Logstash_Format    true
        Logstash_Prefix    builder-log
        Time_Key    @timestamp



  fluent-bit.conf: |
{{ .Values.rawConfig | indent 4 }}

  parsers.conf: |
{{- if .Values.parsers.regex }}
{{- range .Values.parsers.regex }}
    [PARSER]
        Name        {{ .name }}
        Format      regex
        Regex       {{ .regex }}
{{- if .timeKey }}
        Time_Key    {{ .timeKey }}
{{- end }}
{{- if .timeFormat }}
        Time_Format {{ .timeFormat }}
{{- end }}
{{ end }}
{{- end }}
{{- if .Values.parsers.json }}
{{- range .Values.parsers.json }}
    [PARSER]
        Name        {{ .name }}
        Format      json
{{- if .timeKeep }}
        Time_Keep   {{ .timeKeep }}
{{- end }}
{{- if .timeKey }}
        Time_Key    {{ .timeKey }}
{{- end }}
{{- if .timeFormat }}
        Time_Format {{ .timeFormat }}
{{- end }}
{{- if .decodeFieldAs  }}
        Decode_Field_As {{ .decodeFieldAs }} {{ .decodeField | default "log" }}
{{- end}}
{{- if .extraEntries }}
{{ .extraEntries | indent 8 }}
{{- end }}
{{ end }}
{{- end }}
{{- if .Values.parsers.logfmt }}
{{- range .Values.parsers.logfmt }}
    [PARSER]
        Name        {{ .name }}
        Format      logfmt
{{- if .timeKey }}
        Time_Key    {{ .timeKey }}
{{- end }}
{{- if .timeFormat }}
        Time_Format {{ .timeFormat }}
{{- end }}
{{- if .extraEntries }}
{{ .extraEntries | indent 8 }}
{{- end }}
{{ end }}
{{- end }}

{{- end -}}
