{{ if .Values.controller.globalConfiguration.create }}
apiVersion: k8s.nginx.org/v1alpha1
kind: GlobalConfiguration
metadata:
  name: {{ include "nginx-ingress.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nginx-ingress.labels" . | nindent 4 }}
spec:
{{ toYaml .Values.controller.globalConfiguration.spec | indent 2 }}
{{- end }}
