{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
{{- if .Values.controller.serviceAccount.annotations }}
  annotations: {{- toYaml .Values.controller.serviceAccount.annotations | nindent 4 }}
{{- end }}
  name: {{ include "nginx-ingress.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nginx-ingress.labels" . | nindent 4 }}
{{- if .Values.controller.serviceAccount.imagePullSecretName }}
imagePullSecrets:
- name: {{ .Values.controller.serviceAccount.imagePullSecretName }}
{{- end }}
{{- end }}
