kind: Service
apiVersion: v1
metadata:
  name: qxp-web-nginx
  namespace: {{ .Release.Namespace }}
  labels:
    app: qxp-web-nginx
    version: v1
    app.kubernetes.io/name: {{ .Values.app.kubernetes.io.name }}
  annotations:
    kubesphere.io/alias-name: qxp-web-nginx
    kubesphere.io/creator: markduan
    kubesphere.io/serviceType: statelessservice
    servicemesh.kubesphere.io/enabled: 'false'
spec:
  ports:
    - name: http-nginx
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: qxp-web-nginx
    app.kubernetes.io/name: {{ .Values.app.kubernetes.io.name }}
