image:
  repository: docker.io/quanxiang/qxp-web-nginx
  tag: v2.0.0
imagePullSecrets: ""
namespace: ""
service:
  type: ClusterIP
  port: 80
  rpcPort: 0
app:
  kubernetes:
    io:
      name: fronted




