kind: ConfigMap
apiVersion: v1
metadata:
  name: search
  namespace: {{ .Release.Namespace }}

data:
  config.yml: |-
    port: :80
    elasticsearch:
      {{- with.Values.elastic.host }}
      host:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      log: {{ .Values.elastic.log }}