kind: Deployment
apiVersion: apps/v1
metadata:
  name: implant
  namespace: {{ .Release.Namespace }}
  labels:
    app: implant
  annotations:
    deployment.kubernetes.io/revision: '3'
    meta.helm.sh/release-name: implant
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: implant
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: implant
      annotations:
        dapr.io/app-id: implant-dapr
        dapr.io/enabled: 'true'
    spec:
      containers:
        - name: implant
          image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
          command:
            - /ko-app/main.go
            - '-fn-namespace'
            - builder
            - '-svc-namespace'
            - serving
            - '-pubsub'
            - faas-pubsub
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: implantsa
      serviceAccount: implantsa
      securityContext: {}
      imagePullSecrets: 
        - name: {{ .Values.imagePullSecrets }}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
