apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: faas-dapr
  namespace: {{ .Release.Namespace }}
scopes:
- faas-dapr
spec:
  pubsubname: faas-pubsub
  routes:
    default: /event
  topic: lowcode.faas