image:
  name: audit
  repo: docker.io/quanxiang
  tag: v1.1.2
namespace: ""
domain: example.com
mongo_host: ""
args:
  enabled: true
  endpoint: example.com:31198
  ip: xx.xx.xx.xx
kafka:
  value: kafka.{{.}}.svc.cluster.local:9092
redis:
  host: ""
  password: ""
imagePullSecrets: ""
service:
  type: ClusterIP
  port: 80
  rpcPort: 0
nameOverride: ""
fullnameOverride: ""
websocket_hostname: ""
home_hostname: ""
portal_hostname: ""
vendor:
  protocol: ""
  hostname: ""
  port: 0
serviceAccount:
  name: ""
podSecurityContext: {}
securityContext: {}
config:
  jwtKey: ""
  mysql:
    db: ""
    host: mysql.{{.}}.svc.cluster.local:3306
    user: root
    password: qxp1234
    log: true
  redis:
    addrs:
      - redis-cluster-0.redis-cluster-headless.{{.}}.svc.cluster.local:6379
      - redis-cluster-1.redis-cluster-headless.{{.}}.svc.cluster.local:6379
      - redis-cluster-2.redis-cluster-headless.{{.}}.svc.cluster.local:6379
    username: ""
    password: qxp1234
  elastic:
    log: true
    host:
    - http://elasticsearch-master.{{.}}.svc.cluster.local:9200
  kafka:
    broker:
    - kafka.{{.}}.svc.cluster.local:9092
  mongo:
    hosts:
    - mongodb.{{.}}.svc.cluster.local:27017
    direct: false
    credential:
      authMechanism: SCRAM-SHA-1
      authSource: admin
      username: root
      password: qxp1234
      passwordSet: false
  storage:
    option: minio
    urlExpire: 600
    partExpire: 604800
    launch: false
    storages:
    - name: minio
      protocol: http
      domain: home.qxp.com
      accessKey: Minio
      secretKey: Minio123456
      location: us-east-1
      bucketName: default
  email:
    emails: []
ingress:
  enabled: false
  hosts:
  - host: chart-example.local
    paths: []
app:
  kubernetes:
    io:
      name: backend
