apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: message-letter
  namespace: {{ .Release.Namespace }}
spec:
  topic: lowcode.Letter
  route:  /send
  pubsubname: message-kafka-pubsub
scopes:
- letter