{{- if .Values.ingest.enabled }}
apiVersion: {{ template "common.capabilities.statefulset.apiVersion" . }}
kind: StatefulSet
metadata:
  name: {{ include "elasticsearch.ingest.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: ingest
    ## Istio Labels: https://istio.io/docs/ops/deployment/requirements/
    app: ingest
spec:
  updateStrategy:
    type: {{ .Values.ingest.updateStrategy.type }}
    {{- if (eq "OnDelete" .Values.ingest.updateStrategy.type) }}
    rollingUpdate: null
    {{- end }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: ingest
  podManagementPolicy: Parallel
  replicas: {{ .Values.ingest.replicas }}
  serviceName: {{ template "elasticsearch.ingest.fullname" . }}
  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: ingest
        ## Istio Labels: https://istio.io/docs/ops/deployment/requirements/
        app: ingest
        {{- if .Values.ingest.podLabels }}
        {{- include "common.tplvalues.render" (dict "value" .Values.ingest.podLabels "context" $) | nindent 8 }}
        {{- end }}
      annotations:
        {{- if and (include "elasticsearch.createTlsSecret" .) (not .Values.security.tls.ingest.existingSecret) }}
        checksum/tls: {{ include (print $.Template.BasePath "/tls-secret.yaml") . | sha256sum }}
        {{- end }}
        {{- if .Values.ingest.podAnnotations }}
        {{- include "common.tplvalues.render" (dict "value" .Values.ingest.podAnnotations "context" $) | nindent 8 }}
        {{- end }}
    spec:
      {{- include "elasticsearch.imagePullSecrets" . | nindent 6 }}
      {{- if .Values.ingest.hostAliases }}
      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.ingest.hostAliases "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.ingest.schedulerName }}
      schedulerName: {{ .Values.ingest.schedulerName }}
      {{- end }}
      {{- if .Values.ingest.priorityClassName }}
      priorityClassName: {{ .Values.ingest.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.ingest.affinity }}
      affinity: {{- include "common.tplvalues.render" (dict "value" .Values.ingest.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.ingest.podAffinityPreset "component" "ingest" "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.ingest.podAntiAffinityPreset "component" "ingest" "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.ingest.nodeAffinityPreset.type "key" .Values.ingest.nodeAffinityPreset.key "values" .Values.ingest.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- if .Values.ingest.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" .Values.ingest.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.ingest.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.ingest.tolerations "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.ingest.topologySpreadConstraints }}
      topologySpreadConstraints: {{- include "common.tplvalues.render" (dict "value" .Values.ingest.topologySpreadConstraints "context" $) | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ template "elasticsearch.ingest.serviceAccountName" . }}
      {{- if or .Values.ingest.podSecurityContext.enabled .Values.ingest.securityContext.enabled }}
      securityContext:
        {{- if .Values.ingest.podSecurityContext.enabled }}
        {{- omit .Values.ingest.podSecurityContext "enabled" | toYaml | nindent 8 }}
        {{- else }}
        fsGroup: {{ .Values.ingest.securityContext.fsGroup }}
        {{- end }}
      {{- end }}
      {{- if or .Values.ingest.initContainers  .Values.sysctlImage.enabled }}
      initContainers:
        {{- if .Values.sysctlImage.enabled }}
        ## Image that performs the sysctl operation to modify Kernel settings (needed sometimes to avoid boot errors)
        - name: sysctl
          image: {{ include "elasticsearch.sysctl.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          command:
            - /bin/bash
            - -ec
            - |
              {{- include "elasticsearch.sysctlIfLess" (dict "key" "vm.max_map_count" "value" "262144") | nindent 14 }}
              {{- include "elasticsearch.sysctlIfLess" (dict "key" "fs.file-max" "value" "65536") | nindent 14 }}
          securityContext:
            privileged: true
          {{- if .Values.sysctlImage.resources }}
          resources: {{- toYaml .Values.sysctlImage.resources | nindent 12 }}
          {{- end }}
        {{- end }}
        {{- if .Values.ingest.initContainers }}
        {{- include "common.tplvalues.render" (dict "value" .Values.ingest.initContainers "context" $) | nindent 8 }}
        {{- end }}
      {{- end }}
      containers:
        - name: elasticsearch
          image: {{ include "elasticsearch.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          {{- if or .Values.ingest.containerSecurityContext.enabled .Values.ingest.securityContext.enabled }}
          securityContext:
            {{- if .Values.ingest.containerSecurityContext.enabled }}
            {{- omit .Values.ingest.containerSecurityContext "enabled" | toYaml | nindent 12 }}
            {{- else }}
            runAsUser: {{ .Values.ingest.securityContext.runAsUser }}
            {{- end }}
          {{- end }}
          {{- if .Values.diagnosticMode.enabled }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.command "context" $) | nindent 12 }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.args "context" $) | nindent 12 }}
          {{- end }}
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: BITNAMI_DEBUG
              value: {{ ternary "true" "false" (or .Values.image.debug .Values.diagnosticMode.enabled) | quote }}
            - name: ELASTICSEARCH_CLUSTER_NAME
              value: {{ .Values.name | quote }}
            - name: ELASTICSEARCH_CLUSTER_HOSTS
              value: {{ include "elasticsearch.hosts" . | quote }}
            - name: ELASTICSEARCH_TOTAL_NODES
              value: {{ add (ternary .Values.master.autoscaling.minReplicas .Values.master.replicas (eq .Values.master.autoscaling.enabled true)) (ternary .Values.data.autoscaling.minReplicas .Values.data.replicas (eq .Values.data.autoscaling.enabled true)) | quote }}
            - name: ELASTICSEARCH_CLUSTER_MASTER_HOSTS
              {{- $elasticsearchMasterFullname := include "elasticsearch.master.fullname" . }}
              {{- $replicas := int (ternary .Values.master.autoscaling.minReplicas .Values.master.replicas (eq .Values.master.autoscaling.enabled true)) }}
              value: {{ range $i, $e := until $replicas }}{{ $elasticsearchMasterFullname }}-{{ $e }} {{ end }}
            - name: ELASTICSEARCH_MINIMUM_MASTER_NODES
              value: {{ add (div (ternary .Values.master.autoscaling.minReplicas .Values.master.replicas (eq .Values.master.autoscaling.enabled true)) 2) 1 | quote }}
            - name: ELASTICSEARCH_ADVERTISED_HOSTNAME
              value: "$(MY_POD_NAME).{{ include "elasticsearch.ingest.fullname" . }}.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}"
            {{- if .Values.plugins }}
            - name: ELASTICSEARCH_PLUGINS
              value: {{ .Values.plugins | quote }}
            {{- end }}
            - name: ELASTICSEARCH_HEAP_SIZE
              value: {{ .Values.ingest.heapSize | quote }}
            - name: ELASTICSEARCH_IS_DEDICATED_NODE
              value: "yes"
            - name: ELASTICSEARCH_NODE_TYPE
              value: "ingest"
            {{- if .Values.security.enabled }}
            {{- include "elasticsearch.configure.security" . | nindent 12 }}
            {{- end }}
            {{- if .Values.extraEnvVars }}
            {{- include "common.tplvalues.render" ( dict "value" .Values.extraEnvVars "context" $ ) | nindent 12 }}
            {{- end }}
          {{- if or .Values.extraEnvVarsConfigMap .Values.extraEnvVarsSecret }}
          envFrom:
            {{- if .Values.extraEnvVarsConfigMap }}
            - configMapRef:
                name: {{ include "common.tplvalues.render" ( dict "value" .Values.extraEnvVarsConfigMap "context" $ ) }}
            {{- end }}
            {{- if .Values.extraEnvVarsSecret }}
            - secretRef:
                name: {{ include "common.tplvalues.render" ( dict "value" .Values.extraEnvVarsSecret "context" $ ) }}
            {{- end }}
          {{- end }}
          ports:
            - name: {{ include "elasticsearch.httpPortName" . }}
              containerPort: 9200
            - name: transport
              containerPort: 9300
          {{- if not .Values.diagnosticMode.enabled }}
          {{- if .Values.ingest.startupProbe.enabled }}
          startupProbe:
            initialDelaySeconds: {{ .Values.ingest.startupProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.ingest.startupProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.ingest.startupProbe.timeoutSeconds }}
            successThreshold: {{ .Values.ingest.startupProbe.successThreshold }}
            failureThreshold: {{ .Values.ingest.startupProbe.failureThreshold }}
            exec:
              command:
                - /opt/bitnami/scripts/elasticsearch/healthcheck.sh
          {{- else if .Values.ingest.customStartupProbe }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" .Values.ingest.customStartupProbe "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.ingest.livenessProbe.enabled }}
          livenessProbe:
            initialDelaySeconds: {{ .Values.ingest.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.ingest.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.ingest.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.ingest.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.ingest.livenessProbe.failureThreshold }}
            exec:
              command:
                - /opt/bitnami/scripts/elasticsearch/healthcheck.sh
          {{- else if .Values.ingest.customLivenessProbe }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.ingest.customLivenessProbe "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.ingest.readinessProbe.enabled }}
          readinessProbe:
            initialDelaySeconds: {{ .Values.ingest.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.ingest.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.ingest.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.ingest.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.ingest.readinessProbe.failureThreshold }}
            exec:
              command:
                - /opt/bitnami/scripts/elasticsearch/healthcheck.sh
          {{- else if .Values.ingest.customReadinessProbe }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.ingest.customReadinessProbe "context" $) | nindent 12 }}
          {{- end }}
          {{- end }}
          {{- if .Values.ingest.resources }}
          resources: {{- toYaml .Values.ingest.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- if .Values.config }}
            - mountPath: /opt/bitnami/elasticsearch/config/elasticsearch.yml
              name: config
              subPath: elasticsearch.yml
            {{- end }}
            - name: data
              mountPath: /bitnami/elasticsearch/data
            {{- if .Values.security.enabled }}
            - name: elasticsearch-certificates
              mountPath: /opt/bitnami/elasticsearch/config/certs
              readOnly: true
            {{- end }}
            {{- if .Values.extraConfig }}
            - mountPath: /opt/bitnami/elasticsearch/config/my_elasticsearch.yml
              name: config
              subPath: my_elasticsearch.yml
            {{- end }}
            {{- if .Values.extraVolumeMounts }}
            {{- toYaml .Values.extraVolumeMounts | nindent 12 }}
            {{- end }}
            {{- if .Values.initScripts }}
            - name: custom-init-scripts
              mountPath: /docker-entrypoint-initdb.d/init-scripts
            {{- end }}
            {{- if .Values.initScriptsCM }}
            - name: custom-init-scripts-cm
              mountPath: /docker-entrypoint-initdb.d/init-scripts-cm
            {{- end }}
            {{- if .Values.initScriptsSecret }}
            - name: custom-init-scripts-secret
              mountPath: /docker-entrypoint-initdb.d/init-scripts-secret
            {{- end }}
        {{- if .Values.ingest.sidecars }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.ingest.sidecars "context" $) | nindent 8 }}
        {{- end }}
      volumes:
        {{- if or .Values.config .Values.extraConfig }}
        - name: config
          configMap:
            name: {{ include "common.names.fullname" . }}
        {{- end }}
        {{- if .Values.security.enabled }}
        - name: elasticsearch-certificates
          secret:
            secretName: {{ include "elasticsearch.ingest.tlsSecretName" . }}
            defaultMode: 256
        {{- end }}
        {{- if .Values.extraVolumes }}
        {{- toYaml .Values.extraVolumes | nindent 8 }}
        {{- end }}
        {{- if .Values.initScripts }}
        - name: custom-init-scripts
          configMap:
            name: {{ template "elasticsearch.initScripts" . }}
        {{- end }}
        {{- if .Values.initScriptsCM }}
        - name: custom-init-scripts-cm
          configMap:
            name: {{ template "elasticsearch.initScriptsCM" . }}
        {{- end }}
        {{- if .Values.initScriptsSecret }}
        - name: custom-init-scripts-secret
          secret:
            secretName: {{ template "elasticsearch.initScriptsSecret" . }}
            defaultMode: 0755
        {{- end }}
        - name: "data"
          emptyDir: {}
{{- end }}
