{{- if .Values.master.ingress.enabled }}
apiVersion: {{ include "common.capabilities.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.master.ingress.annotations .Values.commonAnnotations }}
  annotations:
    {{- if .Values.master.ingress.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.master.ingress.annotations "context" $) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  rules:
    {{- if .Values.master.ingress.hostname }}
    - http:
        paths:
          - path: {{ .Values.master.ingress.path }}
            {{- if eq "true" (include "common.ingress.supportsPathType" .) }}
            pathType: {{ .Values.master.ingress.pathType }}
            {{- end }}
            backend: {{- include "common.ingress.backend" (dict "serviceName" (include "elasticsearch.master.fullname" .) "servicePort" (include "elasticsearch.httpPortName" .) "context" $)  | nindent 14 }}
      {{- if ne .Values.master.ingress.hostname "*" }}
      host: {{ .Values.master.ingress.hostname }}
      {{- end }}
    {{- end }}
    {{- range .Values.master.ingress.extraHosts }}
    - host: {{ .name }}
      http:
        paths:
          - path: {{ default "/" .path }}
            {{- if eq "true" (include "common.ingress.supportsPathType" $) }}
            pathType: {{ default "ImplementationSpecific" .pathType }}
            {{- end }}
            backend: {{- include "common.ingress.backend" (dict "serviceName" (include "elasticsearch.master.fullname" $) "servicePort" (include "elasticsearch.httpPortName" $) "context" $) | nindent 14 }}
    {{- end }}
  {{- if or .Values.master.ingress.tls .Values.master.ingress.extraTls }}
  tls:
    {{- if .Values.master.ingress.tls }}
    - hosts:
        - {{ .Values.master.ingress.hostname }}
      secretName: {{ printf "%s-tls" .Values.master.ingress.hostname }}
    {{- end }}
    {{- if .Values.master.ingress.extraTls }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.master.ingress.extraTls "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
