image:
  repository: docker.io/quanxiang/goalie
  tag: v2.0.0
namespace: ""
imagePullSecrets: ""
mysql: {}
redis: {}

service:
  type: ClusterIP
  port: 80
  rpcPort: 0

app:
  kubernetes:
    io:
      name: backend

