kind: ConfigMap
apiVersion: v1
metadata:
  name: search
  namespace: {{ .Values.namespace }}

data:
  config.yml: |-
    port: :80
    elasticsearch:
      {{- with .Values.config.elastic.host }}
      host:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      log: {{ .Values.config.elastic.log }}