kind: Service
apiVersion: v1
metadata:
  name: audit
  namespace: {{ .Values.namespace }}
  labels:
    app: audit
    version: v1
    app.kubernetes.io/name: {{ .Values.app.kubernetes.io.name }}
    app.kubernetes.io/version: v1
  annotations:
    kubesphere.io/serviceType: statelessservice
    servicemesh.kubesphere.io/enabled: 'false'
spec:
  ports:
    - name: tcp-80
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: audit
    app.kubernetes.io/version: v1
    app.kubernetes.io/name: {{ .Values.app.kubernetes.io.name }}
  type: ClusterIP
  sessionAffinity: None
