{{- if .Values.global.faas.enabled }}
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ .Values.docker.name }}
  namespace: {{ .Values.namespace }}
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}